// Count diagnostic marker placements from poi_collisions.py using a browser canvas.
const fs=require('fs'),path=require('path'),{chromium}=require('../.artifacts/browser/node_modules/playwright');
(async()=>{const out=path.resolve('bundle/validation/poi-collisions');const browser=await chromium.launch({headless:true});const page=await browser.newPage();const counts={};
for(const file of fs.readdirSync(out).filter(f=>f.endsWith('.png'))){
const data=fs.readFileSync(path.join(out,file)).toString('base64');
counts[file.replace('.png','')]=await page.evaluate(async data=>{const img=new Image();img.src='data:image/png;base64,'+data;await img.decode();const canvas=document.createElement('canvas');canvas.width=img.width;canvas.height=img.height;const ctx=canvas.getContext('2d');ctx.drawImage(img,0,0);const a=ctx.getImageData(0,0,img.width,img.height).data,w=img.width,h=img.height;const pixels=new Set();for(let i=0;i<w*h;i++)if(a[i*4]>240&&a[i*4+1]<15&&a[i*4+2]>240&&a[i*4+3]>240)pixels.add(i);const components=[];while(pixels.size){const first=pixels.values().next().value;pixels.delete(first);const stack=[first];let xmin=w,ymin=h,xmax=0,ymax=0,count=0;while(stack.length){const p=stack.pop(),x=p%w,y=Math.floor(p/w);count++;xmin=Math.min(xmin,x);xmax=Math.max(xmax,x);ymin=Math.min(ymin,y);ymax=Math.max(ymax,y);for(const n of [x>0?p-1:-1,x<w-1?p+1:-1,y>0?p-w:-1,y<h-1?p+w:-1])if(pixels.delete(n))stack.push(n);}if(count>=8)components.push({xmin,ymin,xmax,ymax,pixels:count});}return {count:components.length,components};},data);
}
const views=JSON.parse(fs.readFileSync(path.join(out,'method.json'))).views;
const comparisons=Object.fromEntries(views.map(v=>[v,{local:counts['local-'+v].count,english:counts['en-'+v].count}]));
const report={fixture:{without_collision:counts['collision-off'].count,with_collision:counts['collision-on'].count},comparisons,counts};fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({fixture:report.fixture,comparisons},null,2));for(const [view,pair] of Object.entries(comparisons))if(pair.english>pair.local)throw Error('English POI density exceeds local: '+view);for(const [name,result] of Object.entries(counts))if(name.startsWith('en-'))for(const box of result.components)if(box.xmax-box.xmin>11||box.ymax-box.ymin>11)throw Error('Overlapping diagnostic markers: '+name);if(report.fixture.without_collision<=report.fixture.with_collision||report.fixture.with_collision!==1)throw Error('Collision control failed');})();
